# Nama workflow yang akan muncul di tab Actions di GitHub
name: Deploy to Hostinger FTP (Fast Sync)

# Kapan workflow ini dijalankan
on:
  # Dijalankan setiap kali ada push ke branch 'main'
  push:
    branches: ["main"]
  # Bisa juga dijalankan manual dari tab Actions
  workflow_dispatch:

# Langkah-langkah yang akan dijalankan
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Menjalankan job di mesin virtual Ubuntu
    steps:
      # 1. Mengambil kode dari repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      # 3. Install semua dependencies
      - name: Install Dependencies
        run: npm install

      # 4. Build project jadi file statis di folder 'out'
      - name: Build Project
        run: npm run build

      # 5. Sinkronisasi file ke Hostinger pake lftp (ini bagian yang ngebut!)
      - name: Sync files to Hostinger
        # INI BAGIAN YANG DIGANTI - Pake versi tag yang bener
        uses: sebastianpopp/lftp-action@v2
        with:
          # Kredensial masih sama, diambil dari GitHub Secrets
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Path folder tujuan di hosting
          remoteDir: public_html/buminaeenk.com/
          # Path folder sumber hasil build
          localDir: out/
          # Opsi buat lftp: --delete (hapus file lama), --mirror (sinkronisasi), --verbose (tampilin log)
          options: "-e \"set ftp:ssl-allow no;\" --delete --mirror --verbose"
